### PR TITLE
[Added] Angular v17 Control-Block Syntax

### PR DESCRIPTION
**Pull request by thecodechef**

### CODE REVIEW

**Comment by thecodechef** [comment]
Fixes: #23

**Comment by princemaple** [comment]
Thanks 🙏 I'll probably add some tests and ci before I merge. Cheers!

**Comment by thecodechef** [comment]
No Problem happy to help.

**Comment by princemaple** [comment]
Finally came back home after several long trips. I'll get to this soon. Cheers!

**Comment by princemaple** [comment]
Going to merge this first and then follow up on things.

**Pull request merged**
